name: Docs

on:
  push:
    branches: [main, master]

env:
  CONDA_ENV: {{cookiecutter.package_name}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # needed to push to gh-pages branch

    steps:
      - uses: actions/checkout@v4

      - name: Set up conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: ${{"{{"}} env.CONDA_ENV {{"}}"}}
          environment-file: environment.yml
          auto-activate-base: false
          miniforge-version: latest

      - name: Install package and doc dependencies
        shell: bash -el {0}
        run: pip install -e ".[docs]"

      - name: Deploy docs to GitHub Pages
        shell: bash -el {0}
        run: mkdocs gh-deploy --force
        